photo:
  src: "/config/ptrofile_picture.JPG"
  alt: "Portrait of Arif Nurhidayat"

name: "Arif Nurhidayat"
email: "nurhidayat86@gmail.com"
current_position: "Senior Data Scientist"
headlines:
  - "Senior Data Scientist | FinTech Innovator | Leveraging AI & Analytics to Drive Revenue Growth, Risk Mitigation, and Cost Savings in Lending & Payment Systems"

cv_links:
  - label: "CV (pdf)"
    url: "https://drive.google.com/file/d/1gs4wRzQeLZEJTQw-hljxtVYQz0YqqSPV/view?usp=drive_link"
  - label: "CV (txt)"
    url: "https://drive.google.com/file/d/1cXDXzXt_0KWlKWJ0TywkCzZxYJTOkbmY/view?usp=drive_link"

social_links:
  - label: "LinkedIn"
    url: "https://www.linkedin.com/in/nurhidayatarif/
  - label: "GitHub"
    url: "https://github.com/nurhidayat86"
  - label: "Medium"
    url: "https://medium.com/@nurhidayat86"
